# Function Key Bindings

# Audio controls
bind = , F1, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
bind = , F2, exec, pactl set-sink-volume @DEFAULT_SINK@ -5% && notify-send "🔉 Volume Down"
bind = , F3, exec, pactl set-sink-volume @DEFAULT_SINK@ +5% && notify-send "🔊 Volume Up"
bind = , F4, exec, pactl set-source-mute @DEFAULT_SOURCE@ toggle

# ASUS Profile switch
bind = , F5, exec, ~/.config/hypr/scripts/profile-switch.sh

# Brightness controls
bind = , F6, exec, ~/.config/hypr/scripts/brightness.sh 0%
bind = , F7, exec, ~/.config/hypr/scripts/brightness.sh 5%-
bind = , F8, exec, ~/.config/hypr/scripts/brightness.sh +5%


