# Function Key Bindings (using XF86 key symbols)

# Audio controls
bind = , XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
binde = , XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -5% && notify-send "🔉 Volume Down"
binde = , XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +5% && notify-send "🔊 Volume Up"
bind = , XF86AudioMicMute, exec, pactl set-source-mute @DEFAULT_SOURCE@ toggle

# Brightness controls
binde = , XF86ScreenSaver, exec, ~/.config/hypr/scripts/brightness.sh 0%
binde = , XF86MonBrightnessUp, exec, ~/.config/hypr/scripts/brightness.sh +5%
bind  = , XF86MonBrightnessDown, exec, ~/.config/hypr/scripts/brightness.sh 5%-

