# Main Hyprland Config - Modular
# Only sources all other config files

source = ~/.config/hypr/themes/rose-pine-moon.conf
source = ~/.config/hypr/settings.conf
source = ~/.config/hypr/decoration.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/fnkeys.conf
source = ~/.config/hypr/resize.conf

env = HYPRCURSOR_THEME,Bibata-Modern-Ice
env = HYPRCURSOR_SIZE,24
env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,24

exec-once = ~/.config/hypr/scripts/center_google_signin.sh
