# Monitor settings
monitor=,preferred,auto,1

# Autostart apps
exec-once = mako
exec-once = waybar
exec-once = ~/.config/hypr/scripts/center_google_signin.sh
exec-once = ~/.config/hypr/scripts/profile-switch.sh
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Input settings
input {
    kb_layout = us
    follow_mouse = 1
    sensitivity = 0
    accel_profile = flat
}

# General settings
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = $rose
    col.inactive_border = $overlay
    layout = dwindle
}

